// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN2hKedH5xjCEhjPu24w1CISKUrlDJfMs',
    appId: '1:904496378729:web:1db0c2724db3bfd3aa03f8',
    messagingSenderId: '904496378729',
    projectId: 'hunger-bounce-ebc92',
    authDomain: 'hunger-bounce-ebc92.firebaseapp.com',
    storageBucket: 'hunger-bounce-ebc92.appspot.com',
    databaseURL: "https://hunger-bounce-ebc92-default-rtdb.firebaseio.com",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN5CNTFHXmItubMjaa041ISc0DSfXr3vM',
    appId: '1:904496378729:android:5f000fd433c57b61aa03f8',
    messagingSenderId: '904496378729',
    projectId: 'hunger-bounce-ebc92',
    storageBucket: 'hunger-bounce-ebc92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeHDdkLMzOXBexQqTZHK3OmkxmLw-hBZ0',
    appId: '1:904496378729:ios:20fb9606d8eabb95aa03f8',
    messagingSenderId: '904496378729',
    projectId: 'hunger-bounce-ebc92',
    storageBucket: 'hunger-bounce-ebc92.appspot.com',
    iosClientId:
        '904496378729-1a7j4pnj4if74udm2u60i6gltv06dc6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.sandwichOrderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeHDdkLMzOXBexQqTZHK3OmkxmLw-hBZ0',
    appId: '1:904496378729:ios:20fb9606d8eabb95aa03f8',
    messagingSenderId: '904496378729',
    projectId: 'hunger-bounce-ebc92',
    storageBucket: 'hunger-bounce-ebc92.appspot.com',
    iosClientId:
        '904496378729-1a7j4pnj4if74udm2u60i6gltv06dc6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.sandwichOrderApp',
  );
}
